-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.asignatura
(
    id_asign serial NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cod_asign character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT asignatura_pkey PRIMARY KEY (id_asign),
    CONSTRAINT asignatura_cod_asign_key UNIQUE (cod_asign)
);

CREATE TABLE IF NOT EXISTS public.aulas
(
    id_aula serial NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT aulas_pkey PRIMARY KEY (id_aula)
);

CREATE TABLE IF NOT EXISTS public.docente
(
    id_docen serial NOT NULL,
    nom character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apell character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(20) COLLATE pg_catalog."default" NOT NULL,
    telef character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    fec_ingre timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado_laboral character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT docente_pkey PRIMARY KEY (id_docen),
    CONSTRAINT docente_cedula_key UNIQUE (cedula)
);

CREATE TABLE IF NOT EXISTS public.estudiante
(
    id_studs serial NOT NULL,
    nom character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apell character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_nac timestamp without time zone,
    id_repre integer NOT NULL,
    estado_academico character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT estudiante_pkey PRIMARY KEY (id_studs)
);

CREATE TABLE IF NOT EXISTS public.grado
(
    id_grad serial NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT grado_pkey PRIMARY KEY (id_grad)
);

CREATE TABLE IF NOT EXISTS public.horario
(
    id_horario serial NOT NULL,
    id_docent integer NOT NULL,
    id_aula integer NOT NULL,
    hora time without time zone NOT NULL,
    dia character varying(20) COLLATE pg_catalog."default" NOT NULL,
    id_seccion integer NOT NULL,
    id_asign integer NOT NULL,
    CONSTRAINT horario_pkey PRIMARY KEY (id_horario)
);

CREATE TABLE IF NOT EXISTS public.inventario
(
    id_item serial NOT NULL,
    nombre_articulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(350) COLLATE pg_catalog."default",
    cantidad_total integer NOT NULL DEFAULT 0,
    cantidad_disponible integer NOT NULL DEFAULT 0,
    unidad_medida character varying(20) COLLATE pg_catalog."default",
    ubicacion character varying(100) COLLATE pg_catalog."default",
    estado_conservacion character varying(50) COLLATE pg_catalog."default",
    fec_ultima_revision timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventario_pkey PRIMARY KEY (id_item)
);

CREATE TABLE IF NOT EXISTS public.notas
(
    id_notas serial NOT NULL,
    momento_evalu character varying(50) COLLATE pg_catalog."default",
    descripcion character varying(100) COLLATE pg_catalog."default",
    id_docent integer NOT NULL,
    id_studs integer NOT NULL,
    calificacion character varying(1) COLLATE pg_catalog."default",
    CONSTRAINT notas_pkey PRIMARY KEY (id_notas)
);

CREATE TABLE IF NOT EXISTS public.permisos
(
    id serial NOT NULL,
    nomb character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descrip text COLLATE pg_catalog."default",
    CONSTRAINT permisos_pkey PRIMARY KEY (id),
    CONSTRAINT permisos_nomb_key UNIQUE (nomb)
);

CREATE TABLE IF NOT EXISTS public.representantes
(
    id_represen serial NOT NULL,
    nom character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apell character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(20) COLLATE pg_catalog."default" NOT NULL,
    telef character varying(20) COLLATE pg_catalog."default",
    direccion character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT representantes_pkey PRIMARY KEY (id_represen),
    CONSTRAINT representantes_cedula_key UNIQUE (cedula)
);

CREATE TABLE IF NOT EXISTS public.rol_permisos
(
    rol_id integer NOT NULL,
    permiso_id integer NOT NULL,
    CONSTRAINT rol_permisos_pkey PRIMARY KEY (rol_id, permiso_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    nom character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_nom_key UNIQUE (nom)
);

CREATE TABLE IF NOT EXISTS public.seccion
(
    id_seccion serial NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_grado integer NOT NULL,
    id_turno integer NOT NULL,
    id_docent integer NOT NULL,
    CONSTRAINT seccion_pkey PRIMARY KEY (id_seccion)
);

CREATE TABLE IF NOT EXISTS public.turno
(
    id_turno serial NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT turno_pkey PRIMARY KEY (id_turno)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    pass_hash text COLLATE pg_catalog."default" NOT NULL,
    rol_id integer,
    activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.estudiante
    ADD CONSTRAINT fk_representante FOREIGN KEY (id_repre)
    REFERENCES public.representantes (id_represen) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.horario
    ADD CONSTRAINT fk_asignatura_horario FOREIGN KEY (id_asign)
    REFERENCES public.asignatura (id_asign) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.horario
    ADD CONSTRAINT fk_aula_horario FOREIGN KEY (id_aula)
    REFERENCES public.aulas (id_aula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.horario
    ADD CONSTRAINT fk_docente_horario FOREIGN KEY (id_docent)
    REFERENCES public.docente (id_docen) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.horario
    ADD CONSTRAINT fk_seccion_horario FOREIGN KEY (id_seccion)
    REFERENCES public.seccion (id_seccion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notas
    ADD CONSTRAINT fk_docente_notas FOREIGN KEY (id_docent)
    REFERENCES public.docente (id_docen) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notas
    ADD CONSTRAINT fk_estudiante_notas FOREIGN KEY (id_studs)
    REFERENCES public.estudiante (id_studs) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rol_permisos
    ADD CONSTRAINT rol_permisos_permiso_id_fkey FOREIGN KEY (permiso_id)
    REFERENCES public.permisos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rol_permisos
    ADD CONSTRAINT rol_permisos_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.seccion
    ADD CONSTRAINT fk_docente_seccion FOREIGN KEY (id_docent)
    REFERENCES public.docente (id_docen) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.seccion
    ADD CONSTRAINT fk_grado FOREIGN KEY (id_grado)
    REFERENCES public.grado (id_grad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.seccion
    ADD CONSTRAINT fk_turno FOREIGN KEY (id_turno)
    REFERENCES public.turno (id_turno) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;